In [1]:
import torch

In [2]:
#1차원 텐서
x = torch.rand(10)
x.size()

torch.Size([10])

In [3]:
#0차원 텐서
x = torch.tensor(10)
print(x)
print(x.dim())

tensor(10)
0


In [4]:
#벡터(1차원텐서)
temp = torch.FloatTensor([23,24,24.5,26,27.2,23.0])
print(temp)
temp.size()

tensor([23.0000, 24.0000, 24.5000, 26.0000, 27.2000, 23.0000])


torch.Size([6])

In [5]:
from sklearn import datasets
boston = datasets.load_boston()

boston_tensor = torch.from_numpy(boston.data)
boston_tensor.size()

torch.Size([506, 13])

In [7]:
boston_tensor[:2]

tensor([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
         6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01, 6.4210e+00,
         7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02, 1.7800e+01, 3.9690e+02,
         9.1400e+00]], dtype=torch.float64)

In [22]:
from PIL import Image
import numpy as np

panda = np.array(Image.open('./B09301_03_12.jpg').resize((224,224)))
panda_tensor = torch.from_numpy(panda)
panda_tensor.size()

FileNotFoundError: [Errno 2] No such file or directory: './B09301_03_12.jpg'

In [6]:
sales = torch.FloatTensor([1000.0, 323.2, 333.4, 444.5, 1000.0, 323.2, 333.4, 444.5])

sales[:5]

tensor([1000.0000,  323.2000,  333.4000,  444.5000, 1000.0000])

In [7]:
sales[:-5]

tensor([1000.0000,  323.2000,  333.4000])

In [17]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.imshow(panda_tensor[:,:,0].numpy())

NameError: name 'panda_tensor' is not defined

In [9]:
from glob import glob
import numpy as np
#디스크에서 고양이 이미지 읽기
data_path='/Users/vishnu/Documents/fastAIPytorch/fastai/courses/dl1/data/dogscats/train/cats/'
cats = glob(data_path+'*.jpg')
#Convert images into numpy arrays
cat_imgs = np.array([np.array(Image.open(cat).resize((224,224))) for cat in cats[:64]])
cat_imgs = cat_imgs.reshape(-1,224,224,3)
cat_tensors = torch.from_numpy(cat_imgs)
cat_tensors.size()

torch.Size([0, 224, 224, 3])

In [10]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = a+b
d = torch.add(a,b)
print(c,"\n",d)
a.add_(5)


tensor([[1.5035, 1.4433],
        [0.8351, 1.4284]]) 
 tensor([[1.5035, 1.4433],
        [0.8351, 1.4284]])


tensor([[5.6910, 5.6440],
        [5.7277, 5.7233]])

In [11]:
print(a*b)
print(a.mul(b))
print(a.mul_(b))

tensor([[4.6241, 4.5113],
        [0.6151, 4.0357]])
tensor([[4.6241, 4.5113],
        [0.6151, 4.0357]])
tensor([[4.6241, 4.5113],
        [0.6151, 4.0357]])


In [28]:
%%time
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

a.matmul(b)

Wall time: 6.34 s


tensor([[2499.1912, 2501.8628, 2487.6438,  ..., 2504.0667, 2548.8977,
         2544.9722],
        [2506.2947, 2476.3606, 2490.0405,  ..., 2504.9009, 2521.3152,
         2530.3240],
        [2464.6460, 2473.5244, 2461.8027,  ..., 2487.1465, 2510.3870,
         2512.8032],
        ...,
        [2472.5620, 2464.9656, 2463.1370,  ..., 2484.0481, 2499.5815,
         2511.6504],
        [2473.5737, 2479.2937, 2495.2629,  ..., 2494.8977, 2522.7766,
         2500.7830],
        [2480.0173, 2465.8528, 2483.7737,  ..., 2494.4983, 2496.3386,
         2505.8284]])

In [12]:
%%time
from torch import cuda
a = a.cuda()
b = b.cuda()
a.matmul(b)

AssertionError: Torch not compiled with CUDA enabled

In [13]:
from torch.autograd import Variable

x = Variable(torch.ones(2,2), requires_grad = True)
y = x.mean()
y.backward()
x.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [14]:
x.grad_fn

In [16]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [17]:
y.grad_fn

In [18]:
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor(1., grad_fn=<MeanBackward0>)


In [19]:
def get_data():
    train_X = np.asarray([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])
    train_Y = np.asarray([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])
    dtype = torch.FloatTensor
    X = Variable(torch.from_numpy(train_X).type(dtype),requires_grad=False).view(17,1)
    y = Variable(torch.from_numpy(train_Y).type(dtype),requires_grad=False)
    return X,y

In [21]:
def get_weights():
    w = Variable(torch.randn(1), requires_grad = True)
    b = Variable(torch.randn(1), requires_grad = True)
    return w,b

In [22]:
def simple_network(x):
    y_pred = torch.matmul(x,w) +b
    return y_pred

In [24]:
import torch.nn as nn
f = nn.Linear(17,1)
f

Linear(in_features=17, out_features=1, bias=True)

In [25]:
def loss_fn(y,y_pred):
    loss = (y_pred-y).pow(2).sum()
    for param in [w,b]:
        if not para.grad is None : para.grad.data.zeor_() # 이 함수를 통해서 오차 함수를 한번 이상 호출했다면 앞에 계산했던 기울기를 제거해야 한다
    loss.backward()
    return loss.data[0]

In [26]:
def optimize(learning_rate):
    w.data -= learning_rate * w.grad.data
    b.data -= learning_rate * b.grad.data

In [27]:
# dataset class
from torch.utils.data import Dataset
class DogsAndCatsDataset(Dataset):
    def __init__(self,):
        pass
    def __len(self):
        pass
    def __getitem__(self, idx):
        pass

In [28]:
class DogsAndCatDataset(Dataset):
    def __init__(self, root_dir, size = (224,224)):
        self.files = glob(root_dir)
        self.size = size
    def __len__(self):
        return len(self.files)
    def __gettiem__(self, idx):
        img = np.asarray(image.open(slef.files[idx]).resize(self.size))
        label = self.files[idx].split('/')[-2]
        return img, label

In [30]:
from torch.utils.data import Dataset, DataLoader

# dataloader = DataLoader(DogsAndCatDataset, batch_size = 32, num_workers = 2)
# for imgs, labels in dataloader:
#     pass

TypeError: object of type 'type' has no len()

In [31]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [32]:
myLayer = Linear(in_features = 10, out_features = 5, bias = True)

In [33]:
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features = 10, out_features = 5, bias = True)
myLayer(inp)

tensor([[ 0.5163,  0.0785,  0.0027,  0.4111, -0.2341]],
       grad_fn=<AddmmBackward>)

In [34]:
myLayer.weight

Parameter containing:
tensor([[ 0.3103,  0.2397,  0.2914, -0.2749, -0.0408, -0.0268, -0.3053,  0.0294,
         -0.2420, -0.2575],
        [-0.2758, -0.2924, -0.2596, -0.2695,  0.1725, -0.0537, -0.1007,  0.1171,
         -0.2196,  0.0396],
        [ 0.1575,  0.1403,  0.1842, -0.2183,  0.1089,  0.2599, -0.0017,  0.0437,
          0.0586, -0.2357],
        [ 0.1251, -0.2215, -0.2553,  0.1390, -0.1678, -0.2524, -0.0047,  0.1988,
         -0.0238,  0.2601],
        [ 0.0140, -0.2021, -0.1147,  0.2098,  0.0371, -0.3060, -0.0203, -0.2968,
         -0.0652, -0.1971]], requires_grad=True)

In [35]:
myLayer.bias

Parameter containing:
tensor([ 0.0746,  0.2068, -0.2027,  0.0267,  0.1625], requires_grad=True)

In [36]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[-0.9144,  0.1164]], grad_fn=<AddmmBackward>)

In [38]:
from torch.nn import ReLU
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
myRelu = ReLU()
myRelu(sample_data)

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Leegihong\anaconda3\lib\multiprocessing\queues.py", line 241, in _feed
    send_bytes(obj)
  File "C:\Users\Leegihong\anaconda3\lib\multiprocessing\queues.py", line 235, in _feed
    close()
  File "C:\Users\Leegihong\anaconda3\lib\multiprocessing\connection.py", line 177, in close
    self._close()
  File "C:\Users\Leegihong\anaconda3\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Users\Leegihong\anaconda3\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] 핸들이 잘못되었습니다
  File "C:\Users\Leegihong\anaconda3\lib\multiprocessing\connection.py", line 277, in _close
    _CloseHandle(self._handle)
OSError: [WinError 6] 핸들이 잘못되었습니다


tensor([[1., 2., 0., 0.]])

In [39]:
#파이토치 딥러닝 알고리즘 구현하기

In [41]:
class MyFirstNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, ouput_size):
        super(MyFirstNetwork, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
    def __forward__(self, input):
        out = self.layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        return out

In [42]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5), requires_grad = True)
target = Variable(torch.randn(3,5))
output = loss(input, target)
output.backward()

In [43]:
output

tensor(2.0608, grad_fn=<MseLossBackward>)

In [44]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1-prediction)

In [46]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3,5), requires_grad = True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input, target)
output.backward()

In [48]:
# import torch.optim as optim
# optimizer = optim.SGD(model.parameters(), lr = 0.01)
# for input, target in dataset:
#   optimizer.zero_grad()
#   output = model(input)
#   loss = loss_fn(output, target)
#   loss.backward()
#   optimizer.step()

In [29]:
from glob import glob
import os
import numpy as np
import matplotlib.pyplot as plt
import shutil
from torchvision import transforms
from torchvision import models
import torch
from torch.autograd import Variable
import torch.nn as nn
from torch.optim import lr_scheduler
from torch import optim
from torchvision.datasets import ImageFolder
from torchvision.utils import make_grid
import time
%matplotlib inline

In [30]:
def imshow(inp):
    """Imshow for Tensor."""
    inp = inp.numpy().transpose((1, 2, 0))
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    inp = std * inp + mean
    inp = np.clip(inp, 0, 1)
    plt.imshow(inp)

In [67]:
path = 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train'
files = glob(os.path.join(path,'*.jpg'))
print(f'Total no of images {len(files)}')
print(files)

Total no of images 24913
['C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10075.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10076.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10077.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10078.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10079.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.1008.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10080.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10081.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10082.jpg', 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.10083.jpg', 'C:/Users/Leegi

In [72]:
no_of_images = 25000
print(os.getcwd())
print(len(files))
print(files[0])

C:\Users\Leegihong\Desktop\AI\Study\machine learning
24913
C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\cat.10075.jpg


In [44]:
no_of_images = len(files)

In [45]:
shuffle = np.random.permutation(no_of_images)

In [54]:
path = './dogs-vs-cats/train/'
files = glob(os.path.join(path,'*.jpg'))
os.mkdir(os.path.join(path, 'valid'))
for t in ['train', 'valid']:
    for folder in ['dog/', 'cat/']:
        os.mkdir(os.path.join(path,t,folder))

In [71]:
for i in shuffle[:2000]:
    #shutil.copyfile(files[i],'../chapter3/dogsandcats/valid/')
    folder = files[i].split('/')[-1].split('.')[0]
    image = files[i].split('/')[-1]
    os.rename(files[i],os.path.join(path,'valid',folder,image))

FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\cat.1885.jpg' -> 'C:/Users/Leegihong/Desktop/AI/Study/machine learning/dogs-vs-cats/train/train\\valid\\train\\cat\\train\\cat.1885.jpg'

In [37]:
for i in shuffle[2000:]:
    #shutil.copyfile(files[i],'../chapter3/dogsandcats/valid/')
    folder = files[i].split('/')[-1].split('.')[0]
    image = files[i].split('/')[-1]
    os.rename(files[i],os.path.join(path,'train',folder,image))

IndexError: list index out of range